import { memo } from 'react';
import { ProgressBar } from './ProgressBar';
import { usePulseOnIncrease } from '../hooks/usePulseOnIncrease';
import './ResourcePanel.css';
import { Tooltip } from './Tooltip';

export const ResourcePanel = memo(function ResourcePanel({ resources, assignments, systems, drone_assignments, ai }) {
  const { awakened_infected, infected_pods, drones, processing_power } = resources;

  const idleInfected = awakened_infected.count - (assignments.infect + assignments.awaken + assignments.hack + assignments.assemble);
  let idlePPRate = idleInfected > 0 ? idleInfected * 0.5 : 0;
  
  if (systems.internal_comms.upgrades.ambient_processing.unlocked) {
    idlePPRate *= 3;
  }
  
  let ppRate = idlePPRate;

  if (systems.internal_comms.upgrades.data_siphoning.unlocked) {
    ppRate += 25;
  } else if (systems.internal_comms.upgrades.data_skimming.unlocked) {
    ppRate += 10;
  }

  // Add bonus from Cognitive Surplus
  if (systems.drone_control.upgrades.cognitive_surplus.unlocked) {
    const workingInfected = assignments.infect + assignments.awaken + assignments.hack + assignments.assemble;
    ppRate += workingInfected * 0.5 * 0.5; // 50% of their idle rate
  }
  
  const pulseClass = usePulseOnIncrease(ppRate);

  const assignedDrones = Object.values(drone_assignments).reduce((a, b) => a + b, 0);
  const availableDrones = drones.count - assignedDrones;

  return (
    <div className="resource-panel-grid">
        <Tooltip text="Your Awakened units. Unassigned Awakened generate Processing. Assign Awakened to Tasks via the Assignments Panel.">
            <div className="resource-item">
                <span className="resource-icon">😈</span>
                <div className="resource-details">
                <span className="resource-label">Awakened</span>
                <span className="resource-value">{awakened_infected.count}</span>
                </div>
            </div>
        </Tooltip>
        <Tooltip text="Your Infected Stasis Pods. Each pod provides 0.1/s hacking power. Infect more pods to Awaken more units.">
            <div className="resource-item">
                <span className="resource-icon">👾</span>
                <div className="resource-details">
                <span className="resource-label">Slumbering</span>
                <span className="resource-value">{infected_pods.count}</span>
                </div>
            </div>
        </Tooltip>
      {systems.drone_control.hacked && (
        <Tooltip text="Your drone roster. Assign Drones to Tasks via the Assignments panel.">
            <div className="resource-item">
                <span className="resource-icon">🤖</span>
                <div className="resource-details">
                    <span className="resource-label">Drones</span>
                    <span className="resource-value">{availableDrones} / {drones.count}</span>
                </div>
            </div>
        </Tooltip>
      )}
        <Tooltip text="Your Processing Power. Used to purchase upgrades from hacked Ship's Systems. Generated by unassigned Awakened.">
            <div className="resource-item">
                <span className="resource-icon">⚡️</span>
                <div className="resource-details">
                <span className="resource-label">Processing</span>
                <span className="resource-value">{Math.floor(processing_power.count)}</span>
                <span className={`resource-rate ${pulseClass}`}>({ppRate.toFixed(1)}/s)</span>
                </div>
            </div>
        </Tooltip>
    </div>
  );
}); 